---
title: "Data Science"
author: "Rui Wang"
date: "2018/03/15"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Outline

### Probability
### Statistics
### SQL
### Coding
### Machine Learning
### Case Studies
### How to Summarize

---

# Probability

--

- [Statistical Inference](https://www.amazon.com/Statistical-Inference-George-Casella/dp/0534243126)
    
    * Probability and Basic Statistics: Chapter 1-5
    * Hypothesis Testing: Chapter 6-12

--

- [MIT: Introduction to Probability and Statistics](https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/)
    
    * [Youtube Video List](https://www.youtube.com/playlist?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb)

--

- [A Green Book: A Practical Guide to Quantitative Finance Interview](https://www.amazon.com/Practical-Guide-Quantitative-Finance-Interviews/dp/1438236662)
    
    * Data Science: Chapter 4

--

- [Cheat Sheet](https://static1.squarespace.com/static/54bf3241e4b0f0d81bf7ff36/t/55e9494fe4b011aed10e48e5/1441352015658/probability_cheatsheet.pdf)

    * Cover Most of Knowledge Points

---

# Probability

--

- Cards

    What is probability of getting one pair of card from a deck of 52 cards? 
--
    3/51

--
    What is probability of getting two cards in the same suit from a deck of 52 cards? 
--
    12/51

--
    What’s the probability of getting two cards that are not in the same suit and not a pair from a deck of 52 cards?
--
    36/51
--
- Coins

    You randomly draw a coin from 100 coins - 1 unfair coin (head-head), 99 fair coins (head-tail) and roll it 10 times. If the result is 10 heads, whats the probability that the coin is unfair?
--

    $\frac{1/100}{1/100*1 + 99/100*(1/2)^{10}} = \frac{1024}{1033}$
        

---

# Probability

- Seattle Raining

    You’re about to get on a plane to Seattle. You want to know if you should bring an umbrella. You call 3 random friends of yours who live there and ask each independently if it’s raining. Each of your friends has a 2/3 chance of telling you the truth and a 1/3 chance of messing with you by lying. All 3 friends tell you that “Yes” it is raining. What is the probability that it’s actually raining in Seattle?
--

    p denotes the probablity of raining at Seattle, then we will have the conditional probablity as
    $$\frac{(2/3)^3*p}{(2/3)^3*p + (1/3)^3*(1-p)}$$
--    
    If $p = 1/4$, we have the answer as 8/11.

---

# Statistics

---

# SQL

--

- PRIMARY KEY

    * Uniquely identify each record in a database table
    * Cannot contain NULL values
    * Only one PRIMARY KEY
    
--

- FOREIGN KEY 

    * Used to link two tables together
    * Can contain NULL values
    * Refer to the PRIMARY KEY

--

- Structure

    ```
    select ... from ... 
    join ... on ...
    where ...
    group by ... having ... 
    order by ... 
    ```

---

# SQL

--

- [Intro To Database](https://lagunita.stanford.edu/courses/Engineering/db/2014_1/about)
    
    * [Pratice Questions](https://github.com/wangruinju/SQL_Resources/blob/master/Stanford%20SQL%20practice/SQL%20exercise.Rmd)
    
--

- Online Platforms
    
    * [Leetcode DataBase](https://leetcode.com/problemset/database/) 
    * [Hackerrank](https://www.hackerrank.com/)
    * [Vertabelo Acedemy](https://academy.vertabelo.com/)
    
--

- [Analytical Cases](https://community.modeanalytics.com/sql/tutorial/sql-business-analytics-training/)
    
    * Invertigating a Drop in User Engagement
    * Understanding Search Functionality
    * Validating A/B Test Results

--

- Reference

    * [W3Schools](https://www.w3schools.com/SQl/default.asp)

---

# SQL

- Content Type

    table: content_id | content_type (comment/ post) | target_id

    * If it is comment, target_id is the user_id who posts it.
    * If it is post, then target_id is NULL.
    
    What is the distribution of comments?

--
    
        ```
        select cnt, count(cnt) as freq
        from
            (select content_id, count(target_id) cnt 
            from table 
            group by content_id) a 
        group by cnt;
        ```

---

# Coding

- Python

    * [Problem Solving with Algorithms and Data Structures using Python](http://interactivepython.org/runestone/static/pythonds/index.html)
    * [Google Python Course](https://developers.google.com/edu/python/)
    * [MIT: Introduction to Algorithms](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-spring-2008/)
        * [Youtube Video List](https://www.youtube.com/playlist?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb)
        
--

- [Leetcode](https://leetcode.com/problemset/algorithms/)

    * [My Python Solution](https://github.com/wangruinju/Rui_Python_Leetcode)
    
--

.pull-left[
* Part I
    * Linked List
    * Binary Search
    * Two Points
    * Bit Manipulation
    * Math
    * Stack
    * Hash Table]
    
.pull-right[
* Part II
    * Backtrack
    * Tree
    * DFS
    * BFS
    * String
    * Array
    * Dynamic Programming]
    
---

# Machine Learning

---

# Case Studies

---

# How to Summarize


